### ISSUE TITLE
.pdf converts character `·` to `￿` which causes example.js to fail

### ISSUE THREAD

**Issue by jpolley** [klamping/ui-testing-book#5]
https://github.com/klamping/ui-testing-book/blob/35772b5af63f8aa52fbefaef03e4f133028192fa/manuscript/1.2.6%20Running%20the%20Example%20Test%20Runner%20Test.txt#L42

The code example above is correct. However, when viewing the .pdf from leapub you find that the code example is different. The character `·` is converted to `￿` which causes example.js to fail. 

<img width="1132" alt="pdf screenshot" src="https://user-images.githubusercontent.com/1278333/65164128-4a255700-da0a-11e9-9888-6e960a6646b6.png">

**Comment by klamping** [comment]
Example was updated to use a different page title.
